### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by babafgd** [gilsonmandalogo/hacs-minerstat#3]
FRom minerstat log essage : 

No 'version' key in the manifest file for custom integration 'hacs-minerstat'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'hacs-minerstat'

**Comment by FeroXz** [comment]
I can confirm this. 
Until the fix i added the version manuelly to the manifest.json

**Comment by gilsonmandalogo** [comment]
Fixed in 59640a7efd1f9ff5a870c8c74eb0ad52920d06c5.
