### ISSUE TITLE
Platform error sensor.hacs-minerstat - Integration 'hacs-minerstat' not found.

### ISSUE THREAD

**Issue by danielfinans** [gilsonmandalogo/hacs-minerstat#4]
![hacs-minerstat_check_config](https://user-images.githubusercontent.com/43092606/122823162-4f9a8a00-d2df-11eb-9015-a8c3561a3f3d.PNG)
![hacs-minerstat_sensor](https://user-images.githubusercontent.com/43092606/122823164-50332080-d2df-11eb-9da7-22b3edfbe160.PNG)
![hacs-minerstat_system](https://user-images.githubusercontent.com/43092606/122823165-50cbb700-d2df-11eb-9fe5-d8662eed53db.PNG)
![hacs-minerstat](https://user-images.githubusercontent.com/43092606/122823168-50cbb700-d2df-11eb-9ab7-b257c96bb4b3.PNG)

Hacs-minerstat error on check config.

**Comment by danielfinans** [comment]
Update: Adding version-number in manifest.json fixed this.

**Comment by gilsonmandalogo** [comment]
Related to #3
